{% set version = '0.0.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tfmpvalue
  version: {{ version|replace("-", "_") }}

source:
  fn: TFMPvalue_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/TFMPvalue_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/TFMPvalue/TFMPvalue_{{ version }}.tar.gz

  sha256: cee3aa2d4e22856865d820f695e29a5f23486e5e08cd42cb95a0728f5f9522a1

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcpp

  run:
    - r-base
    - r-rcpp

test:
  commands:
    - $R -e "library('TFMPvalue')"  # [not win]
    - "\"%R%\" -e \"library('TFMPvalue')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/TFMPvalue/index.html
  license: GPL-2
  summary: In putative Transcription Factor Binding Sites (TFBSs)  identification from sequence/alignments,
    we are interested in the significance of certain match score. TFMPvalue provides
    the accurate calculation of P-value with  score threshold for Position Weight Matrices,  or
    the score with given P-value.  This package is an interface to code originally made
    available by  Helene Touzet and Jean-Stephane Varre, 2007,  Algorithms Mol Biol
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
