travis:
  secure:
    BINSTAR_TOKEN: jPB3y/oVd7tY5pI3j3H0h2vofOz4STTRM1kdkhLw7COW+Nlio4X1ZcCD00U5A2dqREbmBaLcraSqlKQqHX69/1k57XJ6OEn0YY0DBvzoTJGP3P39f6rlnorcog2OWv6WiJrHGICmxG65mRuJoDnmc9eSKYDnKt0XL5yPtIJevbaWlQwGg9bFKpWgsAGFKfnBvmRAL6uwA/QXic5UUjJJkjP3OFWL3gQWICtiYl5oWb41ibxP6y/zhC1zQY+Gtmui8pZOK7USvKxvJWqZX6gfrVz4XztZ1j3iEvrgJcOcQCVHcPoSMxT/iQr1ORCECKfYniQOFrsIT1Jx1ThOogTBjhL7EtnVM2c4hkvrZ+pEi/8xiIv0gOqKEUzI5itflqL3k98vyNPtOtU9STJPo4738uzZkviO8maOfcimX79t5RajscuGpMkhtVRj+PlghCINdC5Mcx95YEg9eMyGctwhf6ad+oigpGybKAuFe/mxkTedfH8Xcjxb5PhSN7gWvkdWQuVAR9ZY2VUKeE+3zeNbxSJk/Vwdu/PPzjGWcprCNGjwh5sFEol5GRyPVeNgn0TkdTBqfOk1WafJ502NX8APXruhQcoZucDEfg4qfmeW4U6LconTq30C/aksvuBZu3lom1/XqVMEluqOliYRb89p6rKtDVTOcNyy7AeD4ARoJpM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
